### ISSUE TITLE
very nice ! can it support show chart,  data visiualisation

### ISSUE THREAD

**Issue by xiongzhenglong** [logunify/dsensei#2]
this is yours:
![1682827295430](https://user-images.githubusercontent.com/19340413/235334936-f34afc8e-24cb-4968-a13c-39ece96766e4.png)

and this is my bot, it cannot show chart

![1682825943140](https://user-images.githubusercontent.com/19340413/235334387-b322580f-4664-40e6-b42d-6d9653159d81.png)
and  the cmd shows
![1682827675011](https://user-images.githubusercontent.com/19340413/235335088-7c89613d-0a7b-4e8f-93d2-db2992dc53fe.png)

i guess it needs gtp-4 api?

**Comment by liuyl** [comment]
Hi @xiongzhenglong, thanks for trying this!

I recently rolled back the viz code because of a compatibility issue here: https://github.com/logunify/dsensei/commit/b8ccc2fee42dca650503f1c8a571f6748fcd0d6f
You can patch that change if you want the visualization

I'll also let you know once we add it back!

**Comment by xiongzhenglong** [comment]
i checkout out branch to viz,  but  the problem blow
![22a7c03341e1d22703779eb54280e27](https://user-images.githubusercontent.com/19340413/235394272-780c4cd4-0290-4a4e-add0-3caf93d00fb9.png)
![66f0597698b217ab70e3df250b145d9](https://user-images.githubusercontent.com/19340413/235394273-46ad0209-3807-4a36-902e-680015696d0e.png)

blow is addtion information
![c32504c86d3984c8f886117175da5ea](https://user-images.githubusercontent.com/19340413/235394274-f8138c95-6378-4a68-93a4-6d15199c3cae.png)
![f436baec3991c6fd068c36b7c47bf73](https://user-images.githubusercontent.com/19340413/235395001-c555d8f2-a251-4657-8dae-879b50c14fed.png)

![ee6872b21cd66584234adecdfea99a6](https://user-images.githubusercontent.com/19340413/235394275-9c739390-9e8d-41dc-bf63-0c8ccd18f542.png)
my computer system is  windows 10

**Comment by liuyl** [comment]
Hi @xiongzhenglong, can you shoot me a message on Discord or Slack? I need more information to debug the error.

**Comment by xiongzhenglong** [comment]
![53fc101588e4153c8565a99a325dd94](https://user-images.githubusercontent.com/19340413/235426341-8234627c-1952-4ffa-aabe-ab9a742f00d7.jpg)

i try  to send my vps  account  to you , but  seems not abled

![396e61015cb60682e259dc57a994d4b](https://user-images.githubusercontent.com/19340413/235426460-fb27e0e5-a6bc-4055-863a-c64da4bc5242.png)

**Comment by liuyl** [comment]
fixed https://github.com/logunify/dsensei/commit/6c024d29aeb589b7e7469d61ae54e4341b90cf0c
